# Generated by Django 5.1.7 on 2025-03-09 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('moneySpent', models.DecimalField(decimal_places=6, max_digits=20)),
                ('product', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
