# Generated by Django 5.1.7 on 2025-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
