# Generated by Django 5.0.6 on 2025-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='moneySpent',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
